steps:
  - name: 'golang'
    args: [ 'make', 'docker']

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oathkeeper:latest', '-f', './Dockerfile', '.']

images: ['gcr.io/$PROJECT_ID/oathkeeper:latest']