steps:
  - name: 'golang'
    args: [ 'go', 'build', '-o', 'oathkeeper', '.' ]
    env:
      - CGO_ENABLED=0
      - GOOS=linux
      - GO111MODULE=on
      - GOARCH=amd64
      - GOPROXY=https://proxy.golang.org

  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/oathkeeper:latest', '-f', './Dockerfile', '.']

images: ['gcr.io/$PROJECT_ID/oathkeeper:latest']